import SwiftUI

/// The Patterns tab: the fuller version of every card on Today, on the same page.
///
/// Each card on the Today screen carries a chevron that leads here, so this screen owes each of them
/// an answer at more length than a half-width card could give: the week's totals rather than the
/// day's, every hour of the week rather than one day's, every touched zone rather than the leading
/// two, and every context the user has filed. The observations at the foot are generated by
/// `MobilePatternInsight` in `MobileInsightsView.swift`.
///
/// Wording throughout describes tracked activity and nothing more — what the numbers did, never what
/// it means about the person.
struct MobilePatternsView: View {
    @ObservedObject var detector: Detector

    private var patterns: [MobilePatternInsight] {
        MobilePatternInsight.make(week: detector.week,
                                  hourly: detector.hourOfWeek,
                                  weeklyRate: detector.weeklyRate,
                                  change: detector.weeklyImprovement)
    }

    var body: some View {
        ScrollView(showsIndicators: false) {
            VStack(alignment: .leading, spacing: 12) {
                header
                summaryCard
                HourHeatmapView(day: detector.chartDay)
                weekHoursCard
                zonesCard
                contextCard
                insightsCard
                disclaimer
            }
            .padding(.horizontal, 16)
            .padding(.top, 6)
            .padding(.bottom, 16)
        }
        .background(AwairaPalette.window.ignoresSafeArea())
    }

    // MARK: - Header

    private var header: some View {
        VStack(alignment: .leading, spacing: 1) {
            Text("Patterns")
                .font(.system(size: 20, weight: .semibold))
                .foregroundStyle(AwairaPalette.text)
            Text("The last seven days, kept on this iPhone")
                .font(.system(size: 13))
                .foregroundStyle(AwairaPalette.ink.opacity(0.55))
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    // MARK: - Seven-day summary

    /// The week counted three ways, in the same serif numerals `TodayGlanceCard` gives the day.
    private var summaryCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            eyebrow("SEVEN-DAY SUMMARY")

            HStack(alignment: .top, spacing: 12) {
                metric(label: "TOTAL",
                       value: "\(detector.weeklyTotal)",
                       suffix: nil,
                       tint: AwairaPalette.accent,
                       identifier: "weeklyTotal")

                divider

                metric(label: "PER HOUR",
                       value: detector.weeklyRate > 0 ? String(format: "%.1f", detector.weeklyRate) : "—",
                       suffix: detector.weeklyRate > 0 ? "/hr" : nil,
                       tint: AwairaPalette.rate,
                       identifier: nil)

                divider

                metric(label: "VS LAST WEEK",
                       value: comparison.map { "\($0.amount)" } ?? "—",
                       suffix: comparison == nil ? nil : "%",
                       tint: comparison.map { $0.lower ? AwairaPalette.accent : AwairaPalette.streak }
                           ?? AwairaPalette.soft,
                       identifier: nil)
            }

            if let comparison {
                HStack(spacing: 5) {
                    Image(systemName: comparison.lower ? "arrow.down" : "arrow.up")
                        .font(.system(size: 11, weight: .semibold))
                    Text("\(comparison.amount)% \(comparison.lower ? "lower" : "higher") per tracked hour than the seven days before")
                        .font(.system(size: 13))
                        .fixedSize(horizontal: false, vertical: true)
                }
                .foregroundStyle(comparison.lower ? AwairaPalette.accent : AwairaPalette.streak)
            } else {
                Text("A second week of tracking is what makes a comparison worth stating.")
                    .font(.system(size: 12))
                    .foregroundStyle(AwairaPalette.soft)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .awairaCard(padding: 14)
    }

    /// The rounded percentage and its direction, or `nil` when there is nothing to compare against
    /// or the difference rounds away to nothing. Positive `weeklyImprovement` means *lower*, as
    /// `MobileStatsStore` builds it.
    private var comparison: (amount: Int, lower: Bool)? {
        guard let change = detector.weeklyImprovement else { return nil }
        let amount = Int(abs(change).rounded())
        guard amount >= 1 else { return nil }
        return (amount, change > 0)
    }

    // MARK: - The week, hour by hour

    /// Where the week lands in the day — the evidence behind the "busiest window" observation below.
    ///
    /// Deliberately not one hue at varying opacity: quiet hours sit in the palette's teal and the
    /// busiest come forward in its amber, the same cool-to-warm idea `HourHeatmapView` uses, narrowed
    /// to two stops because a single row of bars cannot carry six.
    private var weekHoursCard: some View {
        let hourly = detector.hourOfWeek
        let maxCount = hourly.max() ?? 0

        return VStack(alignment: .leading, spacing: 10) {
            eyebrow("WHEN, ACROSS THE WEEK")

            if maxCount == 0 {
                Text("No approaches recorded in the last seven days.")
                    .font(.system(size: 12))
                    .foregroundStyle(AwairaPalette.soft)
            } else {
                HStack(alignment: .bottom, spacing: 3) {
                    ForEach(hourly.indices, id: \.self) { hour in
                        VStack(spacing: 4) {
                            RoundedRectangle(cornerRadius: 2, style: .continuous)
                                .fill(barTint(hourly[hour], max: maxCount))
                                .frame(height: barHeight(hourly[hour], max: maxCount))
                            // Every third hour: twenty-four labels collide at a phone's width.
                            Text(hour % 3 == 0 ? Self.hourLabel(hour) : " ")
                                .font(.system(size: 9))
                                .foregroundStyle(AwairaPalette.ink.opacity(0.55))
                                .lineLimit(1)
                                .fixedSize()
                        }
                        .frame(maxWidth: .infinity)
                    }
                }

                if let peak = hourly.indices.max(by: { hourly[$0] < hourly[$1] }), hourly[peak] > 0 {
                    Text("Busiest hour: \(Self.hourLabel(peak))–\(Self.hourLabel((peak + 1) % 24)), \(hourly[peak]) of \(detector.weeklyTotal).")
                        .font(.system(size: 12))
                        .foregroundStyle(AwairaPalette.ink.opacity(0.7))
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .awairaCard(padding: 14)
    }

    /// A bar always has some height so an hour with one approach is not mistaken for an empty one.
    private func barHeight(_ count: Int, max maxCount: Int) -> CGFloat {
        guard count > 0, maxCount > 0 else { return 2 }
        return 6 + 46 * CGFloat(count) / CGFloat(maxCount)
    }

    private func barTint(_ count: Int, max maxCount: Int) -> Color {
        guard count > 0, maxCount > 0 else { return AwairaPalette.ink.opacity(0.07) }
        return AwairaPalette.accent.blended(with: AwairaPalette.rate,
                                            fraction: Double(count) / Double(maxCount))
    }

    // MARK: - Zones

    /// Every zone today's classifier could name, ranked — the half-width card on Today has room for
    /// the two that lead and defers the rest, and the legend, to here.
    private var zonesCard: some View {
        let ranked = TouchZonesCard.ranked(detector.zoneCounts)
        let total = ranked.reduce(0) { $0 + $1.count }

        return VStack(alignment: .leading, spacing: 10) {
            eyebrow("TOUCH LOCATIONS, TODAY")

            if ranked.isEmpty {
                Text("No touches recorded yet today.")
                    .font(.system(size: 12))
                    .foregroundStyle(AwairaPalette.soft)
            } else {
                ForEach(ranked, id: \.zone) { entry in
                    breakdownRow(label: TouchZonesCard.displayNames[entry.zone] ?? entry.zone,
                                 count: entry.count,
                                 total: total,
                                 tint: zoneTint(entry.count, max: ranked[0].count))
                }

                legend
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .awairaCard(padding: 14)
    }

    /// The same three bands the head's pills use, so a colour means one thing across both screens.
    private func zoneTint(_ count: Int, max maxCount: Int) -> Color {
        let share = maxCount > 0 ? Double(count) / Double(maxCount) : 0
        return share >= 0.66 ? TouchZonesCard.high : (share >= 0.33 ? TouchZonesCard.medium
                                                                   : TouchZonesCard.low)
    }

    private var legend: some View {
        HStack(spacing: 12) {
            legendKey("High", TouchZonesCard.high)
            legendKey("Medium", TouchZonesCard.medium)
            legendKey("Low", TouchZonesCard.low)
            Spacer(minLength: 0)
        }
        .padding(.top, 2)
    }

    private func legendKey(_ label: String, _ tint: Color) -> some View {
        HStack(spacing: 5) {
            Circle()
                .fill(tint)
                .frame(width: 8, height: 8)
            Text(label)
                .font(.system(size: 11))
                .foregroundStyle(AwairaPalette.ink.opacity(0.7))
        }
    }

    // MARK: - Context

    /// What the user said they were doing, in their own vocabulary. A label that has since rolled off
    /// the card still reads as words — `MobileContextOptions.label(for:)` un-slugs whatever it cannot
    /// find on offer today.
    private var contextCard: some View {
        let ranked = detector.contextCounts
            .filter { $0.value > 0 }
            .sorted { $0.value == $1.value ? $0.key < $1.key : $0.value > $1.value }
        let total = ranked.reduce(0) { $0 + $1.value }

        return VStack(alignment: .leading, spacing: 10) {
            eyebrow("WHAT WAS HAPPENING, TODAY")

            if ranked.isEmpty {
                Text("Nothing tagged yet. The chips on Today wake up after a touch.")
                    .font(.system(size: 12))
                    .foregroundStyle(AwairaPalette.soft)
                    .fixedSize(horizontal: false, vertical: true)
            } else {
                ForEach(ranked, id: \.key) { entry in
                    breakdownRow(label: MobileContextOptions.label(for: entry.key),
                                 count: entry.value,
                                 total: total,
                                 tint: AwairaPalette.navSelected)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .awairaCard(padding: 14)
    }

    // MARK: - Observations

    private var insightsCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            eyebrow("OBSERVATIONS")

            if patterns.isEmpty {
                Text("A few more days of tracking and there will be something worth saying here.")
                    .font(.system(size: 12))
                    .foregroundStyle(AwairaPalette.soft)
                    .fixedSize(horizontal: false, vertical: true)
            } else {
                ForEach(patterns) { insight in
                    HStack(alignment: .top, spacing: 10) {
                        Image(systemName: insight.symbol)
                            .font(.system(size: 14))
                            .foregroundStyle(insight.tint)
                            .frame(width: 20, alignment: .center)
                        VStack(alignment: .leading, spacing: 3) {
                            Text(insight.title)
                                .font(.system(size: 14, weight: .semibold))
                                .foregroundStyle(AwairaPalette.text)
                                .fixedSize(horizontal: false, vertical: true)
                            Text(insight.detail)
                                .font(.system(size: 12))
                                .foregroundStyle(AwairaPalette.ink.opacity(0.7))
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .awairaCard(padding: 14)
    }

    private var disclaimer: some View {
        Text("These observations describe recent tracking, not your health or intent.")
            .font(.system(size: 12))
            .foregroundStyle(AwairaPalette.soft)
            .fixedSize(horizontal: false, vertical: true)
            .padding(.horizontal, 2)
    }

    // MARK: - Shared pieces

    private func eyebrow(_ text: String) -> some View {
        Text(text)
            .font(.system(size: 11, weight: .medium))
            .kerning(0.6)
            .foregroundStyle(AwairaPalette.ink.opacity(0.72))
    }

    private var divider: some View {
        Rectangle()
            .fill(AwairaPalette.cardBorder)
            .frame(width: 1, height: 52)
    }

    private func metric(label: String, value: String, suffix: String?, tint: Color,
                        identifier: String?) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label)
                .font(.system(size: 11, weight: .medium))
                .kerning(0.6)
                .foregroundStyle(AwairaPalette.ink.opacity(0.72))
                .lineLimit(1)
                .minimumScaleFactor(0.7)
            HStack(alignment: .lastTextBaseline, spacing: 0) {
                Text(value)
                    .font(.system(size: 32, design: .serif))
                    .foregroundStyle(tint)
                    .monospacedDigit()
                    .accessibilityIdentifier(identifier ?? "")
                if let suffix {
                    Text(suffix)
                        .font(.system(size: 16, design: .serif))
                        .foregroundStyle(tint.opacity(0.85))
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    /// One line of a ranked breakdown: the name, its share as a bar, and the count.
    private func breakdownRow(label: String, count: Int, total: Int, tint: Color) -> some View {
        let share = total > 0 ? Double(count) / Double(total) : 0
        return HStack(spacing: 10) {
            Text(label)
                .font(.system(size: 13))
                .foregroundStyle(AwairaPalette.text)
                .lineLimit(1)
                .frame(width: 110, alignment: .leading)

            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule()
                        .fill(AwairaPalette.ink.opacity(0.07))
                    Capsule()
                        .fill(tint)
                        // A visible stub for a share too small to draw, so a row is never a bar of
                        // nothing next to a count of one.
                        .frame(width: max(4, geo.size.width * share))
                }
            }
            .frame(height: 8)

            Text("\(count)")
                .font(.system(size: 13))
                .monospacedDigit()
                .foregroundStyle(AwairaPalette.ink.opacity(0.7))
                .frame(width: 28, alignment: .trailing)
            Text("\(Int((share * 100).rounded()))%")
                .font(.system(size: 12))
                .monospacedDigit()
                .foregroundStyle(AwairaPalette.soft)
                .frame(width: 36, alignment: .trailing)
        }
    }

    /// An hour as the user's locale writes it ("9 AM", "21"). Built from a real date because the
    /// format is localized — `HourHeatmapView` labels its columns from the same template.
    private static func hourLabel(_ hour: Int) -> String {
        let calendar = Calendar.current
        let date = calendar.date(bySettingHour: hour, minute: 0, second: 0, of: Date()) ?? Date()
        return hourFormatter.string(from: date)
    }

    private static let hourFormatter: DateFormatter = {
        let f = DateFormatter()
        f.setLocalizedDateFormatFromTemplate("j")
        return f
    }()
}
